import contentBoundaryType from 'fontoxml-base-flow/src/contentBoundaryType.js';
import defaultTraverser from 'fontoxml-families/src/shared/defaultTraverser.js';
import addAttributeIndex from 'fontoxml-indices/src/addAttributeIndex.js';

import InsertFormulaCommand from './api/InsertFormulaCommand.js';
import FormulaTemplate from './api/FormulaTemplate.js';

const TEXT_SELECTOR_FOR_FORMULA =
	'self::text()[preceding-sibling::processing-instruction()[name(.)="fontoxml-formula"] and following-sibling::processing-instruction()[name(.)="fontoxml-formula-end"]]';

export default function configureFormula(sxModule) {
	addAttributeIndex(null, 'id', 'http://www.fontoxml.com/functions', 'id-lookup');

	sxModule.configure('commands').addCommand('insert-formula', new InsertFormulaCommand());

	sxModule
		.configure('fontoxml-base-flow')
		.forNodesMatching(TEXT_SELECTOR_FOR_FORMULA)
		.isAutogenerated(false)
		.isAutomergeable(false)
		.isClosed(false)
		.isDetached(false)
		.isIgnoredForNavigation(false)
		.isRemovableIfEmpty(true)
		.isSplittable(false)
		.nodeIsContent(false)
		.selectBeforeDelete(true)
		.withContentBoundaryType(contentBoundaryType.NONE);

	sxModule
		.configure('fontoxml-block-flow')
		.forNodesMatching(TEXT_SELECTOR_FOR_FORMULA)
		.withBlockTypes([]);

	sxModule
		.configure('fontoxml-families')
		.forNodesMatching(TEXT_SELECTOR_FOR_FORMULA)
		.isSheetFrame(false)
		.withInnerLayoutType('inline')
		.withLayoutType('inline');

	sxModule
		.configure('fontoxml-templated-views')
		.stylesheet('content')
		.renderNodesMatching(TEXT_SELECTOR_FOR_FORMULA)
		.withTraverser(defaultTraverser)
		.withTemplate(new FormulaTemplate());
}
